/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Division} from './division';


export interface CaseRead {
    [key: string]: any | any;


    id: any | null;
    case_number: any | null;
    business_unit: any | null;
    division: Division;
    ic: any | null;
    investment_center_name: any | null;
    psp: any | null;
    project_description: any | null;
    project_on_rda: any | null;
    case_type: any | null;
    responsible: any | null;
    legal_responsible: any | null;
    finance_responsible: any | null;
    real_case: any | null;
    expected_legal_costs: any | null;
    accumulated_legal_costs: any | null;
    accumulated_court_costs: any | null;
    expected_court_costs: any | null;
    start_date_proceeding: any | null;
    end_date_proceeding: any | null;
    interest_date: any | null;
    interest_rate_percent: any | null;
    implenia_share_percent: any | null;
    value_in_dispute: any | null;
    currency: any | null;
    subject_matter: any | null;
    status_proceeding: any | null;
    country_party_relation: any | null;
    claimant_respondent: any | null;
    revision: any | null;
    claimant: any | null;
    repondent_of_claim: any | null;
    considered_accounting: any | null;
    opportunities_risks: any | null;
    interests: any | null;
    comments: any | null;
    next_milestone: any | null;
    date_next_milestone: any | null;
    case_status: any | null;
    review_status: any | null;
}
