/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { CaseDetail } from '../model/models';
import { Configuration }                                     from '../configuration';
import {QuestionRead} from "../model/questionRead";
import {CaseRecordUpdateOutput} from "../model/caseRecordUpdateOutput";


export interface CreateRecordcasesCaseIdRecordsPostRequestParams {
    caseId: any;
    requestBody: { [key: string]: any; } | null;
}

export interface ReadCaseByIdcasesIdGetRequestParams {
    id: any;
}

export interface ReadCasescasesGetRequestParams {
    status?: any;
}

export interface SaveQuestionquestionsPostRequestParams {
    requestBody: { [key: string]: any; } | null;
}

export interface UpdateRecordcasesCaseIdRecordsRecordIdPutRequestParams {
    caseId: any;
    recordId: any;
    requestBody: { [key: string]: any; } | null;
}


export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Record
     *
* @param requestParameters
     */
    createRecordcasesCaseIdRecordsPost(requestParameters: CreateRecordcasesCaseIdRecordsPostRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Read Case By Id
     *
* @param requestParameters
     */
    readCaseByIdcasesIdGet(requestParameters: ReadCaseByIdcasesIdGetRequestParams, extraHttpRequestParams?: any): Observable<CaseDetail>;

    /**
     * Read Cases
     *
* @param requestParameters
     */
    readCasescasesGet(requestParameters: ReadCasescasesGetRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Read Questions
     *
*/
    readQuestionsquestionsGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Save Question
     *
* @param requestParameters
     */
    saveQuestionquestionsPost(requestParameters: SaveQuestionquestionsPostRequestParams, extraHttpRequestParams?: any): Observable<QuestionRead>;

    /**
     * Update Record
     *
* @param requestParameters
     */
    updateRecordcasesCaseIdRecordsRecordIdPut(requestParameters: UpdateRecordcasesCaseIdRecordsRecordIdPutRequestParams, extraHttpRequestParams?: any): Observable<CaseRecordUpdateOutput>;

}
