/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Configuration }                                     from '../configuration';
import {QuestionRead} from "../model/questionRead";


export interface SaveQuestionApiQuestionsPostRequestParams {
    requestBody: { [key: string]: any; } | null;
}


export interface QuestionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Read Questions
     *
*/
    readQuestionsApiQuestionsGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Save Question
     *
* @param requestParameters
     */
    saveQuestionApiQuestionsPost(requestParameters: SaveQuestionApiQuestionsPostRequestParams, extraHttpRequestParams?: any): Observable<QuestionRead>;

}
